
version: "3.0"

services:
    
    weblogic:
        image: store/oracle/weblogic:12.2.1.4-dev-200117    # Esto es un comentario
        container_name: miweblogic
        ports:
            - 7001:7001
            - 7011:7011
            - 7021:7021
            - 9002:9002
        volumes:
            - /home/ubuntu/environment/curso/instalaciones/weblogic:/u01/oracle/properties
            - /home/ubuntu/environment/dominio:/u01/oracle/user_projects
        environment:
            DOMAIN_NAME: base_domain

# docker-compose up -d